### ISSUE TITLE
Exception while synchronising Fastmail CardDAV

### ISSUE THREAD

**Issue by duncan-bayne** [skarra/ASynK#102]
I get most of the way through the synchronisation, then ASynK crashes:

```
[09:17:30.558     INFO] =====================================================
INFO:root:225 new entries to be synched.
[09:17:30.558     INFO] 225 new entries to be synched.
DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default/    Method: REPORT
DEBUG:root:Received Response: HTTP/1.1 207 Multi-Status

CRITICAL:root:Exception (<xml.etree.ElementTree.QName object at 0x7f9f19995b10>) while syncing profile duncan
[09:17:33.593 CRITICAL] Exception (<xml.etree.ElementTree.QName object at 0x7f9f19995b10>) while syncing profile duncan
CRITICAL:root:Traceback (most recent call last):
  File "/home/duncan/ASynK/asynk/asynk_core.py", line 401, in op_sync
    result = sync.sync(self.get_sync_dir())
  File "/home/duncan/ASynK/asynk/sync.py", line 300, in sync
    ret2 = sl2.sync_to_folder(self.get_f1())
  File "/home/duncan/ASynK/asynk/sync.py", line 498, in sync_to_folder
    res1 = self.send_news_to_folder(df)
  File "/home/duncan/ASynK/asynk/sync.py", line 444, in send_news_to_folder
    items = self.fold.find_items(self.get_news())
  File "/home/duncan/ASynK/asynk/folder_cd.py", line 177, in find_items
    etag = item.getNodeProperties()[davxml.getetag]
KeyError: <xml.etree.ElementTree.QName object at 0x7f9f19995b10>

[09:17:33.593 CRITICAL] Traceback (most recent call last):
  File "/home/duncan/ASynK/asynk/asynk_core.py", line 401, in op_sync
    result = sync.sync(self.get_sync_dir())
  File "/home/duncan/ASynK/asynk/sync.py", line 300, in sync
    ret2 = sl2.sync_to_folder(self.get_f1())
  File "/home/duncan/ASynK/asynk/sync.py", line 498, in sync_to_folder
    res1 = self.send_news_to_folder(df)
  File "/home/duncan/ASynK/asynk/sync.py", line 444, in send_news_to_folder
    items = self.fold.find_items(self.get_news())
  File "/home/duncan/ASynK/asynk/folder_cd.py", line 177, in find_items
    etag = item.getNodeProperties()[davxml.getetag]
KeyError: <xml.etree.ElementTree.QName object at 0x7f9f19995b10>
```

I'm running Python 2.7.12 and the latest ASynK from Git (05b8118039aa2d8193a7f738b03e559e5d2becce).

**Comment by skarra** [comment]
Sorry about that. 

I do not have a fastmail account, so I will need your help in debugging this issue further. For starters, can you answer the following questions:

- Are you a new user? 
- Does a Dry Run work?
- Were you able to successfully do a sync before this?
- What is the other end you are trying to sync?
- Can you invoke asynk with ```--log=debug``` and you should get an idea of the specific contact that is causing ASynK to barf. Based on your knowledge of your addressbook, can you spot anything different about that contact. An example is it has unicode characters, or some fields not present in the contacts that synched successfully, etc.

**Comment by duncan-bayne** [comment]
> Sorry about that. 

Hey, no need to apologise!  This is a great tool.  I just hope I can help debug this one issue I'm having.

> Are you a new user?

Nope - I used ASynK a few years ago with Fastmail, and it was fine (once FM fixed a bug in their CardDAV implementation).

> Does a Dry Run work?

Yes!  That was surprising - running the command with `--dry-run` succeeded.  It still fails without, though.

> Were you able to successfully do a sync before this?

Yes, but that was some time ago (months, years?).  

> What is the other end you are trying to sync?

`https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/Default`

> Can you invoke asynk with --log=debug and you should get an idea of the specific contact that is causing ASynK to barf. Based on your knowledge of your addressbook, can you spot anything different about that contact. An example is it has unicode characters, or some fields not present in the contacts that synched successfully, etc.

Running with `--log=debug` didn't shed any more light on the problem I'm afraid; I got a whole lot more information about the contacts that _did_ synchronise ...

```
[17:40:50.232    DEBUG] Modified CardDAV Contact:              No Name 2368dab2-131c-432d-9569-66f681547950
DEBUG:root:New      CardDAV Contact:              No Name f1c14cdb-5468-4f13-b3f3-be1d60c9fb9a
[17:40:50.233    DEBUG] New      CardDAV Contact:              No Name f1c14cdb-5468-4f13-b3f3-be1d60c9fb9a
DEBUG:root:Modified CardDAV Contact:        Cheap Domains 8e059c956f
[17:40:50.233    DEBUG] Modified CardDAV Contact:        Cheap Domains 8e059c956f
DEBUG:root:New      CardDAV Contact:           Bek & Adam 19b49c7b-1af7-4623-ae48-131940864780
```

... then the same failure at the end:

```
[17:40:50.772     INFO] 225 new entries to be synched.
DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default/    Method: REPORT
[17:40:51.855    DEBUG] Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default/       Method: REPORT
DEBUG:root:Received Response: HTTP/1.1 207 Multi-Status

[17:40:53.066    DEBUG] Received Response: HTTP/1.1 207 Multi-Status

CRITICAL:root:Exception (<xml.etree.ElementTree.QName object at 0x7fdbf0980bd0>) while syncing profile duncan
[17:40:54.249 CRITICAL] Exception (<xml.etree.ElementTree.QName object at 0x7fdbf0980bd0>) while syncing profile duncan
CRITICAL:root:Traceback (most recent call last):
  File "/home/duncan/ASynK/asynk/asynk_core.py", line 401, in op_sync
    result = sync.sync(self.get_sync_dir())
  File "/home/duncan/ASynK/asynk/sync.py", line 300, in sync
    ret2 = sl2.sync_to_folder(self.get_f1())
  File "/home/duncan/ASynK/asynk/sync.py", line 498, in sync_to_folder
    res1 = self.send_news_to_folder(df)
  File "/home/duncan/ASynK/asynk/sync.py", line 444, in send_news_to_folder
    items = self.fold.find_items(self.get_news())
  File "/home/duncan/ASynK/asynk/folder_cd.py", line 177, in find_items
    etag = item.getNodeProperties()[davxml.getetag]
KeyError: <xml.etree.ElementTree.QName object at 0x7fdbf0980bd0>

[17:40:54.250 CRITICAL] Traceback (most recent call last):
  File "/home/duncan/ASynK/asynk/asynk_core.py", line 401, in op_sync
    result = sync.sync(self.get_sync_dir())
  File "/home/duncan/ASynK/asynk/sync.py", line 300, in sync
    ret2 = sl2.sync_to_folder(self.get_f1())
  File "/home/duncan/ASynK/asynk/sync.py", line 498, in sync_to_folder
    res1 = self.send_news_to_folder(df)
  File "/home/duncan/ASynK/asynk/sync.py", line 444, in send_news_to_folder
    items = self.fold.find_items(self.get_news())
  File "/home/duncan/ASynK/asynk/folder_cd.py", line 177, in find_items
    etag = item.getNodeProperties()[davxml.getetag]
KeyError: <xml.etree.ElementTree.QName object at 0x7fdbf0980bd0>
```

**Comment by skarra** [comment]
So you're synching from one CardDAV source to another, with one of them being Fastmail?

**Comment by duncan-bayne** [comment]
No, I'm _trying_ to synchronise BBDB with Fastmail; I wonder now if I've misconfigured something if that's how it seems :)

**Comment by skarra** [comment]
I just looked up my fastmail asynk setup from the last time you raised an issue. Can you confirm this is how it looks in your ~/.asynk/state.json ? Yours should structurally look similar, particularly the coll_1 and coll_2 parts.

```
160       "fastmailbb" : { "coll_1" : { "dbid" : "bb",
161               "foid" : "default",
162               "stid" : "/Users/sriramkarra/dotfiles/.bbdb.misc/bbdb.fastmail"
163             },
164           "coll_2" : { "dbid" : "cd",
165               "foid" : "default",
166               "stid" : "https://carddav.messagingengine.com/dav/addressbooks/user/skarra@fastmail.com/"
167             },
168           "conflict_resolve" : "1",
169           "items" : { "1a274be8-312b-11e4-af69-20c9d0851eb3" : "b62c08e7afbeffc4f7d71935ea334149",
170               "cc00ed7a-9fde-11e4-aaf5-20c9d0851eb3" : "a11385dda0f2f70d2d16ef9b66404227"
171             },
172           "last_sync_start" : "2015-07-13T01:38:10.91Z",
173           "last_sync_stop" : "2015-07-13T01:38:19.97Z",
174           "olgid" : null,
175           "sync_dir" : "SYNC2WAY",
176           "sync_state" : null
177         },
```

**Comment by duncan-bayne** [comment]
Nothing much like it, I'm afraid:

```
{ "app_root" : "/home/duncan/ASynK",
  "asynk_user_dir" : "/home/duncan/.asynk.carddav",
  "default_profile" : "duncan",
  "file_version" : 5,
  "profiles" : { "defbbbb" : { "coll_1" : { "dbid" : "bb",
                                            "foid" : "default",
                                            "stid" : "~/.bbdb"
                                          },
                               "coll_2" : { "dbid" : "bb",
                                            "foid" : "default",
                                            "stid" : "/tmp/asynk.bbdb"
                                          },
                               "conflict_resolve" : "bb",
                               "items" : {  },
                               "last_sync_start" : "2016-09-29T23:10:34.98Z",
                               "last_sync_stop" : "2016-09-29T23:10:34.99Z",
                               "olgid" : null,
                               "sync_dir" : "SYNC2WAY"
                             },
                 "defolbb" : { "coll_1" : { "dbid" : "ol",
                                            "foid" : null,
                                            "stid" : null
                                          },
                               "coll_2" : { "dbid" : "bb",
                                            "foid" : null,
                                            "stid" : "~/.bbdb"
                                          },
                               "conflict_resolve" : "ol",
                               "last_sync_start" : "1980-01-01T00:00:00.00+00:00",
                               "last_sync_stop" : "1980-01-01T00:00:00.00+00:00",
                               "olgid" : 36865,
                               "sync_dir" : "SYNC2WAY"
                             },
                 "duncan" : { "coll_1" : { "dbid" : "bb",
                                           "foid" : "default",
                                           "stid" : "/home/duncan/.emacs.d/bbdb"
                                         },
                              "coll_2" : { "dbid" : "cd",
                                           "foid" : "default",
                                           "stid" : "https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/Default"
                                         },
                              "conflict_resolve" : "1",
                              "last_sync_start" : "1980-01-01T00:00:00.00+00:00",
                              "last_sync_stop" : "1980-01-01T00:00:00.00+00:00",
                              "olgid" : null,
                              "sync_dir" : "SYNC2WAY",
                              "sync_state" : null
                            }
               }
}
```

**Comment by skarra** [comment]
Hm, just a wild attempt: can you manually edit the 'duncan' profile part  from this:

```
"https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/Default"
```

to this:

```
"https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/"
```

**Comment by duncan-bayne** [comment]
Sorry, haven't had an opportunity to do the above in the past four years.  Happy to close this issue if you'd like.
