### ISSUE TITLE
ASynK tries to open a file named like my password

### ISSUE THREAD

**Issue by daedadu** [skarra/ASynK#122]
Hi I'm running 
`python asynk.py --op=list-folders --db gc --user-dir /Volumes/NONAME/aktenordner/emacs/asynk --store test.db < login.auth`

The login.auth contains my google username and password. When I execute this, ASynK tries to open a file that is named like my password. How do I fix this. ASynK is pulled from repo 1 hour ago.
It's trying to oauth, but as far as I'm not getting this wrong, oauth should mean I have to allow access on the google page, but I did not explicitly do this or have been asked to do so.

    Applying base config from file /Users/angus/ASynK/config/config_v8.json...
    Applying base config from file /Users/angus/ASynK/config/config_v8.json...done
    Applying user customizations from file /Volumes/NONAME/aktenordner/emacs/asynk/config.py...
    Applying user customizations from file /Volumes/NONAME/aktenordner/emacs/asynk/config.py...done
    INFO:root:Debug logging to file: /Volumes/NONAME/aktenordner/emacs/asynk/logs/asynk_logs.2018-07-29.22-53-22.629841
    [22:53:22.629     INFO] Debug logging to file: /Volumes/NONAME/aktenordner/emacs/asynk/logs/asynk_logs.2018-07-29.22-53-22.629841
    DEBUG:root:Command line: "asynk.py --op=list-folders --db gc --user-dir /Volumes/NONAME/aktenordner/emacs/asynk --store test.db"
    INFO:root:Deleting log files older than 7 days, if any...
    [22:53:22.630     INFO] Deleting log files older than 7 days, if any...
    INFO:root:Deleting log files older than 7 days, if any...done
    [22:53:22.631     INFO] Deleting log files older than 7 days, if any...done
    DEBUG:root:PIMDB gc does not have email_domains.
    DEBUG:root:PIMDB gc does not have notes_map
    DEBUG:root:PIMDB gc does not have phones_map
    INFO:root:Attempting to log into Google...
    [22:53:22.631     INFO] Attempting to log into Google...
    INFO:root:Starting to listen on port 1977...
    [22:53:22.631     INFO] Starting to listen on port 1977...
    INFO:root:Staring the wonderful oAuth dance...
    [22:53:22.632     INFO] Staring the wonderful oAuth dance...
    Please enter username for gc1: Enter password for gc1: Traceback (most recent call last):
      File "asynk.py", line 325, in <module>
        main()
      File "asynk.py", line 322, in main
        asynk.dispatch()
      File "/Users/angus/ASynK/asynk/asynk_core.py", line 97, in dispatch
        res = getattr(self, self.get_op())()
      File "/Users/angus/ASynK/asynk/asynk_core.py", line 116, in op_list_folders
        self._login()
      File "/Users/angus/ASynK/asynk/asynk_core.py", line 85, in _login
        coll.login()
      File "/Users/angus/ASynK/asynk/state_collection.py", line 336, in login
        self.get_username(), self.get_pwd())
      File "/Users/angus/ASynK/asynk/pimdb_gc.py", line 71, in __init__
        self.gc_init()
      File "/Users/angus/ASynK/asynk/pimdb_gc.py", line 279, in gc_init
        self.credentials = self._oauth_dance(storage)
      File "/Users/angus/ASynK/asynk/pimdb_gc.py", line 257, in _oauth_dance
        redirect_uri='http://localhost:%d' % port)
      File "/usr/local/lib/python2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
        return wrapped(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
        cache=cache)
      File "/usr/local/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
        return _loadfile(filename)
      File "/usr/local/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 125, in _loadfile
        exc.strerror, exc.errno)
    oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', '/Users/angus/ASynK/mypassword', 'No such file or directory', 2)

**Comment by skarra** [comment]
Google Contacts API cannot be used with username and password, but oAuth. Please refer to this doc page for how to set up authentication to use Google contacts: https://github.com/skarra/ASynK/blob/master/README-google-oauth.md

**Comment by daedadu** [comment]
Tank you very much, that worked. I tried the list-folders subfunction an the login worked.
