### ISSUE TITLE
Error Principal does not have any addressbook home

### ISSUE THREAD

**Issue by ian-kelling** [skarra/ASynK#124]
The server is radicale which I run.

```
Please enter username for cd1: Enter password for cd1: Found current principal path: /ian/
DEBUG:root:Sending Request URL: /ian/   Method: PROPFIND
DEBUG:root:Received Response: HTTP/1.1 207 Unknown

DEBUG:root:Found principal: Invalid Principal
DEBUG:root:CDPIMDB.fetch_folders(): Begin
DEBUG:root:Exploring following root paths: []
DEBUG:root:CDPIMDB.fetch_folders(): Done.
Traceback (most recent call last):
  File "./asynk.py", line 325, in <module>
    main()
  File "./asynk.py", line 322, in main
    asynk.dispatch()
  File "/a/opt/ASynK/asynk/asynk_core.py", line 97, in dispatch
    res = getattr(self, self.get_op())()
  File "/a/opt/ASynK/asynk/asynk_core.py", line 116, in op_list_folders
    self._login()
  File "/a/opt/ASynK/asynk/asynk_core.py", line 85, in _login
    coll.login()
  File "/a/opt/ASynK/asynk/state_collection.py", line 295, in login
    self.get_username(), self.get_pwd())
  File "/a/opt/ASynK/asynk/pimdb_cd.py", line 57, in __init__
    self.set_def_folders()
  File "/a/opt/ASynK/asynk/pimdb_cd.py", line 118, in set_def_folders
    root     = self.get_def_root_folder_path()
  File "/a/opt/ASynK/asynk/pimdb_cd.py", line 305, in get_def_root_folder_path
    raise CardDAVPrincipalNotFoundError(e)
pimdb_cd.CardDAVPrincipalNotFoundError: Principal does not have any addressbook home
```

**Comment by skarra** [comment]
Thanks for trying ASynK!
