### ISSUE TITLE
CardDav sync with Posteo.de : unknown or illegal ISO-8601 date format: u'2018-08-06 14:43:29 +0000' 

### ISSUE THREAD

**Issue by sokolgeo** [skarra/ASynK#132]
Hello! Trying the latest ASynK to sync BBDB with CardDav server on https://posteo.de

Getting the following error:

> DEBUG:root:Refreshing Contacts for folder default...
ERROR:root:Error (unknown or illegal ISO-8601 date format: u'2018-08-06 14:43:29 +0000') parsing vCard object for pimp_Nbt1c0r6g5S19hqKYbGUSL3iAjdi5FT9sML9VF2CBQ
[20:48:53.936    ERROR] Error (unknown or illegal ISO-8601 date format: u'2018-08-06 14:43:29 +0000') parsing vCard object for pimp_Nbt1c0r6g5S19hqKYbGUSL3iAjdi5FT9sML9VF2CBQ
Traceback (most recent call last):
  File "asynk.py", line 325, in <module>
    main()
  File "asynk.py", line 322, in main
    asynk.dispatch()
  File "/home/user/ASynK/asynk/asynk_core.py", line 97, in dispatch
    res = getattr(self, self.get_op())()
  File "/home/user/ASynK/asynk/asynk_core.py", line 392, in op_sync
    sync.prep_lists(self.get_sync_dir())
  File "/home/user/ASynK/asynk/sync.py", line 284, in prep_lists
    return self._prep_lists_2_way(self.get_f1(), self.get_f2())
  File "/home/user/ASynK/asynk/sync.py", line 180, in _prep_lists_2_way
    f2.prep_sync_lists(f1.get_dbid(), f2sl)
  File "/home/user/ASynK/asynk/folder_cd.py", line 65, in prep_sync_lists
    curi  = self.get_itemids(pname, destid)
  File "/home/user/ASynK/asynk/folder_cd.py", line 118, in get_itemids
    self._refresh_contacts()
  File "/home/user/ASynK/asynk/folder_cd.py", line 312, in _refresh_contacts
    cons  = self.find_items(hrefs)
  File "/home/user/ASynK/asynk/folder_cd.py", line 181, in find_items
    cd = CDContact(self, vco=vobject.readOne(vcf.text), itemid=key)
  File "/home/user/ASynK/asynk/contact_cd.py", line 96, in __init__
    self.init_props_from_vco(vco)
  File "/home/user/ASynK/asynk/contact_cd.py", line 182, in init_props_from_vco
    self._snarf_dates_from_vco(vco)
  File "/home/user/ASynK/asynk/contact_cd.py", line 437, in _snarf_dates_from_vco
    dt = pimdb_cd.CDPIMDB.parse_vcard_time(vco.rev.value)
  File "/home/user/ASynK/asynk/pimdb_cd.py", line 203, in parse_vcard_time
    t = iso8601.parse(t)
  File "/home/user/ASynK/lib/iso8601.py", line 22, in parse
    raise ValueError, "unknown or illegal ISO-8601 date format: " + `s`
ValueError: unknown or illegal ISO-8601 date format: u'2018-08-06 14:43:29 +0000'

Is there anything to be done on ASynK side rather than trying to make folks on Posteo.de to re-configure their CardDav server? Thank you.

**Comment by skarra** [comment]
It's not a valid ISO 8601, so I don't want to fix anything in ASynK to workaround this kind of thing. You could try locally patching your version of the relevant files in ASynK to rewrite the string before letting ASynK parse the received .vcf file.

You could write your own function to do the above, and then call it instead of directly calling iso8601.parse() below. I think that might be enough, and worse case you may have to repeat the inverse on the way out.

```
asynk/pimdb_cd.py", line 203, in parse_vcard_time
t = iso8601.parse(t)
```
