### ISSUE TITLE
Server responded with: 400, Invalid request.

### ISSUE THREAD

**Issue by vonpupp** [skarra/ASynK#133]
Hello,

I am trying to sync gc to bb. I am getting the following error:

[02:11:38.952     INFO] Successfully created BBDB entry for        ...
[02:11:38.952     INFO] Saving BBDB File /home/av/.bbdb...
[02:11:39.591     INFO] Saving BBDB File /home/av/.bbdb...done
[02:11:39.617     INFO] Uploading Remote ItemIDs to Google...
[02:11:40.796 CRITICAL] Exception (Server responded with: 400, Invalid request.) while syncing profile vonpuppgcbb
[02:11:40.798 CRITICAL] Traceback (most recent call last):
  File "/home/av/bin/ASynK/asynk/asynk_core.py", line 401, in op_sync
    result = sync.sync(self.get_sync_dir())
  File "/home/av/bin/ASynK/asynk/sync.py", line 299, in sync
    ret1 = sl1.sync_to_folder(self.get_f2())
  File "/home/av/bin/ASynK/asynk/sync.py", line 499, in sync_to_folder
    res1 = self.send_news_to_folder(df)
  File "/home/av/bin/ASynK/asynk/sync.py", line 447, in send_news_to_folder
    res = res and self.fold.writeback_sync_tags(self.get_pname(), items)
  File "/home/av/bin/ASynK/asynk/folder_gc.py", line 452, in writeback_sync_tags
    rf = self.get_db().exec_batch(f, extra_headers=eh)
  File "/home/av/bin/ASynK/asynk/pimdb_gc.py", line 365, in exec_batch
    gdata.contacts.client.DEFAULT_BATCH_URL)
  File "/home/av/bin/ASynK/asynk/pimdb_gc.py", line 50, in patched_post
    desired_class=desired_class, **kwargs)
  File "/home/av/bin/ASynK/lib/gdata/client.py", line 319, in request
    RequestError)
RequestError: Server responded with: 400, Invalid request.

I had a look at the source code and It is breaking on line 452 of [folder_gc]. I have no clue why.

[folder_gc]: https://github.com/skarra/ASynK/blob/master/asynk/folder_gc.py#L452

**Comment by dinojr** [comment]
I'm experiencing the same problem with a 2 way sync between google contacts and bbdb. I can provide additional information and run further tests.
