### ISSUE TITLE
AsynK web broken?

### ISSUE THREAD

**Issue by lockywolf** [skarra/ASynK#134]
Hello!

The link to AsynK web on https://asynk.io/app seems to lead to a python exception.

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/4a2384f6b69cef45/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/4a2384f6b69cef45/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/4a2384f6b69cef45/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/4a2384f6b69cef45/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/4a2384f6b69cef45/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/4a2384f6b69cef45/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~karra-asynk/5.405417662136639504/asynk.py", line 412, in get
    params = self._get()
  File "/base/data/home/apps/s~karra-asynk/5.405417662136639504/asynk.py", line 375, in _get
    mp_did = self.get_mp_distinct_id()
  File "/base/data/home/apps/s~karra-asynk/5.405417662136639504/asynk.py", line 307, in get_mp_distinct_id
    return token['distinct_id']
TypeError: string indices must be integers, not str
```

**Comment by skarra** [comment]
Hi; sorry yes the webapp is a bit broken; and I have not been able to find the time to look into it. Thanks for your interest!
