### ISSUE TITLE
Sync between two Google Contacts accounts

### ISSUE THREAD

**Issue by paour** [skarra/ASynK#52]
When I try to set up a profile to sync from user1@gmail.com and user2@gmail.com, ASynK misunderstands and creates a profile to sync user2@gmail.com to user2@gmail.com.

Even if I manually change state.json to fix the profile, I don't think I can provide the password either with .netrc (the naming doesn't seem to support providing the password for two accounts using the same provider) or the command-line.

Could you support GC-GC sync?

**Comment by skarra** [comment]
I have added support for this in a branch called refactor-a

Can you give it a try?

**Comment by paour** [comment]
I'm getting

```
./asynk.py --op sync --name plpgp --dry-run
Traceback (most recent call last):
  File "./asynk.py", line 31, in <module>
    from   asynk_core       import Asynk, AsynkParserError
  File "/home/paour/ASynK/asynk/asynk_core.py", line 48, in <module>
    from   state_collection import collection_id_to_class as coll_id_class
  File "/home/paour/ASynK/asynk/state_collection.py", line 71, in <module>
    netrc = NetrcAuth()
  File "/home/paour/ASynK/asynk/state_collection.py", line 54, in __init__
    logging.warning('Ignoring ~/.netrc: could not parse it (%s)', e)
NameError: global name 'logging' is not defined
```

**Comment by skarra** [comment]
Fixed that error; please pull now. But please note that asynk could not parse your netrc file. You will have to check to see there are no errors in syntax.

**Comment by paour** [comment]
I'm also getting (after a pull):

```
$ ./asynk.py --op list-profiles
Applying base config from file /home/paour/ASynK/config/config_v7.json...
Applying base config from file /home/paour/ASynK/config/config_v7.json...done
Applying user customizations from file /home/paour/.asynk/config.py...
Applying user customizations from file /home/paour/.asynk/config.py...done
[18:51:36.164     INFO] Debug logging to file: /home/paour/.asynk/logs/asynk_logs.2015-01-20.18-51-36.164910
Traceback (most recent call last):
  File "./asynk.py", line 302, in <module>
    main()
  File "./asynk.py", line 294, in main
    asynk = AsynkBuilderC(uinps, config, alogger).asynk
  File "./asynk.py", line 170, in __init__
    self.validate_and_snarf_uinps(uinps)
  File "./asynk.py", line 254, in validate_and_snarf_uinps
    (re.search('_profile', self.asynk.get_op()))):
NameError: global name 're' is not defined
```

**Comment by skarra** [comment]
fixed; please pull again

**Comment by paour** [comment]
That seems to be working (asynk doesn't prompt me for my password). I've only tried a dry-run so far.
