### ISSUE TITLE
KeyError: 'dry_run' on first run

### ISSUE THREAD

**Issue by DamienCassou** [skarra/ASynK#54]
I'm trying to launch ASynK (2.0.0-rc2) for the first time. Here is the output I get:

```
$ ./result/bin/asynk.py 
Applying base config from file config/config_v7.json...
Applying base config from file config/config_v7.json...done
Applying user customizations from file /home/cassou/.asynk/config.py...
Applying user customizations from file /home/cassou/.asynk/config.py...done
[15:15:09.256     INFO] Debug logging to file: /home/cassou/.asynk/logs/asynk_logs.2015-01-22.15-15-09.256145
Traceback (most recent call last):
  File "./result/bin/asynk.py", line 1125, in <module>
    main()
  File "./result/bin/asynk.py", line 80, in main
    asynk.dispatch()
  File "./result/bin/asynk.py", line 508, in dispatch
    if not self.is_dry_run():
  File "./result/bin/asynk.py", line 903, in is_dry_run
    return self._get_att('dry_run')
  File "./result/bin/asynk.py", line 858, in _get_att
    return self.atts[att]
KeyError: 'dry_run'
```

**Comment by DamienCassou** [comment]
I confirm the problem with 1.1.0

**Comment by skarra** [comment]
Can you try from the tip of master?

**Comment by DamienCassou** [comment]
@skarra same thing :-(. I'm available on instant messaging if you want faster feedback. Please check my website for more information http://damiencassou.seasidehosting.st.

**Comment by skarra** [comment]
Ah, I see. A fix for this minor problem is in the ```refactor-a``` branch which will be merged shortly. You can apply the following patch to your master branch to make progress.

```
diff --git a/asynk.py b/asynk.py
index 4801051..aa1205c 100755
--- a/asynk.py
+++ b/asynk.py
@@ -416,6 +416,7 @@ class Asynk:
 
         self.set_exuser(None)
         self.set_expw(None)
+        self.set_dry_run(True)
 
         ## More to come here...
```
