### ISSUE TITLE
KeyError: 'nc' with carddav and baikal

### ISSUE THREAD

**Issue by DamienCassou** [skarra/ASynK#55]
Hi,

I'm facing this error message:

```
$ ./result/bin/asynk.py --op=sync --name carddav2bbdb --dry-run
Applying base config from file ./config/config_v7.json...
Applying base config from file ./config/config_v7.json...done
Applying user customizations from file /home/cassou/.asynk/config.py...
Applying user customizations from file /home/cassou/.asynk/config.py...done
[10:36:22.307     INFO] Debug logging to file: /home/cassou/.asynk/logs/asynk_logs.2015-01-23.10-36-22.306931
[10:36:22.372     INFO] Logging into CardDAV server: https://www.<someserver>.org/baikal/card.php - user: xxx...
Traceback (most recent call last):
  File "asynk.py", line 1126, in <module>
    main()
  File "asynk.py", line 80, in main
    asynk.dispatch()
  File "asynk.py", line 512, in dispatch
    res = getattr(self, self.get_op())()
  File "asynk.py", line 776, in op_sync
    pname = self._load_profile()
  File "asynk.py", line 1120, in _load_profile
    self._login()
  File "asynk.py", line 300, in _login
    self.set_db(db1id, getattr(self, login_func)())
  File "asynk.py", line 1062, in login_cd
    self.get_cduser(), self.get_cdpw())
  File "./asynk/pimdb_cd.py", line 55, in __init__
    self.cd_init()
  File "./asynk/pimdb_cd.py", line 280, in cd_init
    logging=self.get_client_logging())
  File "./lib/caldavclientlibrary/client/account.py", line 23, in __init__
    self.session = CalDAVSession(server, port, ssl, user, pswd, principal, root, logging)
  File "./lib/caldavclientlibrary/client/clientsession.py", line 77, in __init__
    self._initCalDAVState()
  File "./lib/caldavclientlibrary/client/clientsession.py", line 84, in _initCalDAVState
    self._discoverPrincipal()
  File "./lib/caldavclientlibrary/client/clientsession.py", line 89, in _discoverPrincipal
    current = self.getCurrentPrincipalResource(self.rootPath)
  File "./lib/caldavclientlibrary/client/clientsession.py", line 396, in getCurrentPrincipalResource
    hrefs = self.getHrefListProperty(rurl, davxml.current_user_principal)
  File "./lib/caldavclientlibrary/client/clientsession.py", line 267, in getHrefListProperty
    self.runSession(request)
  File "./lib/caldavclientlibrary/client/clientsession.py", line 821, in runSession
    self.doSession(request)
  File "./lib/caldavclientlibrary/client/clientsession.py", line 855, in doSession
    if not self.initialise(self.server, self.rootPath.relativeURL()):
  File "./lib/caldavclientlibrary/protocol/webdav/session.py", line 54, in initialise
    self.sendRequest(request)
  File "./lib/caldavclientlibrary/protocol/http/session.py", line 81, in sendRequest
    self.doRequest(request)
  File "./lib/caldavclientlibrary/client/clientsession.py", line 915, in doRequest
    hdrs = request.getRequestHeaders()
  File "./lib/caldavclientlibrary/protocol/http/requestresponse.py", line 124, in getRequestHeaders
    self.addHeaders(result)
  File "./lib/caldavclientlibrary/protocol/http/requestresponse.py", line 150, in addHeaders
    self.session.addHeaders(hdrs, self)
  File "./lib/caldavclientlibrary/protocol/http/session.py", line 47, in addHeaders
    self.getAuthorization().addHeaders(hdrs, request)
  File "./lib/caldavclientlibrary/protocol/http/authentication/digest.py", line 52, in addHeaders
    os.write(" nc=\"%s\"" % (self.fields['nc'],))
KeyError: 'nc'
```

I have this profile:

```json
{ [...]
  "profiles" : {
      "carddav2bbdb" : {
          "coll_1" : { "dbid" : "cd",
                       "foid" : "default",
                       "stid" : "https://www.<someserver>.org/baikal/card.php"
                     },
          "coll_2" : { "dbid" : "bb",
                       "foid" : "default",
                       "stid" : "/home/cassou/.bbdb"
                     },
          "conflict_resolve" : "cd",
          "last_sync_start" : "1980-01-01T00:00:00.00+00:00",
          "last_sync_stop" : "1980-01-01T00:00:00.00+00:00",
          "olgid" : null,
          "sync_dir" : "SYNC2WAY",
          "sync_state" : null
      }
  }
}
```

The `caldavclientlibrary` is at this version:

```shell
$ cd lib/caldavclientlibrary
$ git status
HEAD detached at 06699b0
nothing to commit, working directory clean
```

The server is a `Baikal 0.2.4`.

**Comment by skarra** [comment]
I have tested with Baikal 0.2.5 and tip of master works fine. 

(a) Can you try upgrading
(b) can you run with --log=debug and send me the output?

**Comment by DamienCassou** [comment]
Ok, I updated to `Baikal 0.2.7`. The error is now:

```
$ asynk.py --op=sync --name carddav2bbdb --dry-run --log=debug
[12:55:51.330     INFO] Debug logging to file: /home/cassou/.asynk/logs/asynk_logs.2015-01-23.12-55-51.330331
[12:55:51.393     INFO] Logging into CardDAV server: https://www.<someserver>.org/baikal-ng/card.php - user: xxx...
[12:55:51.393    DEBUG] PIMDB cd does not have email_domains.
[12:55:51.393    DEBUG] PIMDB cd does not have postal_map
[12:55:51.394    DEBUG] PIMDB cd does not have notes_map
[12:55:51.394    DEBUG] PIMDB cd does not have phones_map
[12:55:51.394    DEBUG] Sending request OPTIONS to server www.<someserver>.org/baikal-ng/card.php...
[12:55:51.874    DEBUG] Sending Request URL: /baikal-ng/card.php	Method: OPTIONS
[12:55:51.928    DEBUG] Received Response: HTTP/1.1 200 OK

[12:55:51.929    DEBUG] Sending Request URL: /baikal-ng/card.php	Method: PROPFIND
[12:55:52.067    DEBUG] Received Response: HTTP/1.1 200 OK

[12:55:52.070 CRITICAL] Could not open connection to Carddav Server (https://www.<someserver>.org). Error: Code: 200, Reason: OK
Applying base config from file ./config/config_v7.json...
Applying base config from file ./config/config_v7.json...done
Applying user customizations from file /home/cassou/.asynk/config.py...
Applying user customizations from file /home/cassou/.asynk/config.py...done
Traceback (most recent call last):
  File "./bin/.asynk.py-wrapped", line 1126, in <module>
    main()
  File "./bin/.asynk.py-wrapped", line 80, in main
    asynk.dispatch()
  File "./bin/.asynk.py-wrapped", line 512, in dispatch
    res = getattr(self, self.get_op())()
  File "./bin/.asynk.py-wrapped", line 776, in op_sync
    pname = self._load_profile()
  File "./bin/.asynk.py-wrapped", line 1120, in _load_profile
    self._login()
  File "./bin/.asynk.py-wrapped", line 300, in _login
    self.set_db(db1id, getattr(self, login_func)())
  File "./bin/.asynk.py-wrapped", line 1062, in login_cd
    self.get_cduser(), self.get_cdpw())
  File "./asynk/pimdb_cd.py", line 55, in __init__
    self.cd_init()
  File "./asynk/pimdb_cd.py", line 280, in cd_init
    logging=self.get_client_logging())
  File "./lib/caldavclientlibrary/client/account.py", line 23, in __init__
    self.session = CalDAVSession(server, port, ssl, user, pswd, principal, root, logging)
  File "./lib/caldavclientlibrary/client/clientsession.py", line 77, in __init__
    self._initCalDAVState()
  File "./lib/caldavclientlibrary/client/clientsession.py", line 84, in _initCalDAVState
    self._discoverPrincipal()
  File "./lib/caldavclientlibrary/client/clientsession.py", line 89, in _discoverPrincipal
    current = self.getCurrentPrincipalResource(self.rootPath)
  File "./lib/caldavclientlibrary/client/clientsession.py", line 396, in getCurrentPrincipalResource
    hrefs = self.getHrefListProperty(rurl, davxml.current_user_principal)
  File "./lib/caldavclientlibrary/client/clientsession.py", line 289, in getHrefListProperty
    self.handleHTTPError(request)
  File "./lib/caldavclientlibrary/client/clientsession.py", line 959, in handleHTTPError
    request.getStatusReason()))
caldavclientlibrary.protocol.http.util.HTTPError: Code: 200, Reason: OK
```

**Comment by skarra** [comment]
Hm, I upgraded my own Baikal version to v0.2.7 and still have no issues.  That is a really strange error - 200 :) Currently I am at a total loss as to the cause of your problem...

**Comment by DamienCassou** [comment]
@skarra is my json file extract above reasonable? What about the url?

**Comment by skarra** [comment]
It looks reasonable. The only weird thing I can spot there is the path for the asynk driver you invoke - although I have no idea why that would affect anything. But stil worth a try - can you just invoke asynk from the root directory itself instead of the bin/asynk ... ?

**Comment by skarra** [comment]
I am really not sure what the problem is. I just cloned a completely fresh copy of ASynK (HEAD of master) into /tmp and tried to sync with a local Baikal (0.2.7) install, and I did not run into the issue above. Can you pull ASynK afresh and try again:

```
git clone git@github.com:skarra/ASynK.git asynk
cd asynk
git submodule update --init --recursive
```

**Comment by DamienCassou** [comment]
Ok, I spent some more time on it. I've used git to fetch asynk. And python is at 2.7.9. The error is now:

```
Traceback (most recent call last):
  File "/nix/store/xyxcwsymmzwdziydxydixzwi91nlq63s-ASynK-2.1.0-rc2/bin/.asynk.py-wrapped", line 302, in <module>
    main()
  File "/nix/store/xyxcwsymmzwdziydxydixzwi91nlq63s-ASynK-2.1.0-rc2/bin/.asynk.py-wrapped", line 299, in main
    asynk.dispatch()
  File "/nix/store/xyxcwsymmzwdziydxydixzwi91nlq63s-ASynK-2.1.0-rc2/asynk/asynk_core.py", line 97, in dispatch
    res = getattr(self, self.get_op())()
  File "/nix/store/xyxcwsymmzwdziydxydixzwi91nlq63s-ASynK-2.1.0-rc2/asynk/asynk_core.py", line 366, in op_sync
    pname = self._load_profile()
  File "/nix/store/xyxcwsymmzwdziydxydixzwi91nlq63s-ASynK-2.1.0-rc2/asynk/asynk_core.py", line 584, in _load_profile
    self._login()
  File "/nix/store/xyxcwsymmzwdziydxydixzwi91nlq63s-ASynK-2.1.0-rc2/asynk/asynk_core.py", line 85, in _login
    coll.login()
  File "/nix/store/xyxcwsymmzwdziydxydixzwi91nlq63s-ASynK-2.1.0-rc2/asynk/state_collection.py", line 292, in login
    self.get_username(), self.get_pwd())
  File "/nix/store/xyxcwsymmzwdziydxydixzwi91nlq63s-ASynK-2.1.0-rc2/asynk/pimdb_cd.py", line 55, in __init__
    self.cd_init()
  File "/nix/store/xyxcwsymmzwdziydxydixzwi91nlq63s-ASynK-2.1.0-rc2/asynk/pimdb_cd.py", line 280, in cd_init
    logging=self.get_client_logging())
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/client/account.py", line 23, in __init__
    self.session = CalDAVSession(server, port, ssl, user, pswd, principal, root, logging)
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/client/clientsession.py", line 77, in __init__
    self._initCalDAVState()
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/client/clientsession.py", line 84, in _initCalDAVState
    self._discoverPrincipal()
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/client/clientsession.py", line 89, in _discoverPrincipal
    current = self.getCurrentPrincipalResource(self.rootPath)
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/client/clientsession.py", line 396, in getCurrentPrincipalResource
    hrefs = self.getHrefListProperty(rurl, davxml.current_user_principal)
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/client/clientsession.py", line 267, in getHrefListProperty
    self.runSession(request)
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/client/clientsession.py", line 817, in runSession
    self.doSession(request)
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/client/clientsession.py", line 851, in doSession
    if not self.initialise(self.server, self.rootPath.relativeURL()):
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/protocol/webdav/session.py", line 54, in initialise
    self.sendRequest(request)
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/protocol/http/session.py", line 78, in sendRequest
    self.needConnection()
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/protocol/http/session.py", line 108, in needConnection
    self.openConnection()
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/protocol/http/session.py", line 113, in openConnection
    self.openSession()
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/client/clientsession.py", line 793, in openSession
    self.connect = SmartHTTPConnection(self.server, self.port, self.ssl)
  File "/nix/store/zq9anyzl321j6551vi0a0534qbm9jxaw-python2.7-caldavclientlibrary-asynk-asynkdev/lib/python2.7/site-packages/caldavclientlibrary/client/httpshandler.py", line 65, in SmartHTTPConnection
    raise RuntimeError("Cannot connect via with SSLv23 or SSLv3")
RuntimeError: Cannot connect via with SSLv23 or SSLv3
```

**Comment by DamienCassou** [comment]
After some more debugging, I found the cause: the server I'm using has a self-signed certificate and I didn't find a way to make it acceptable to the ssl module cleanly. So, I decided to hack the CalDAVClientLibrary to ignore certificate errors (I'm thus vulnerable to man-in-the-middle attacks):

```diff
diff --git a/caldavclientlibrary/client/httpshandler.py b/caldavclientlibrary/client/httpshandler.py
index 7d3bfae..41df753 100644
--- a/caldavclientlibrary/client/httpshandler.py
+++ b/caldavclientlibrary/client/httpshandler.py
@@ -34,7 +34,8 @@ https_v3_connects = set()
 def SmartHTTPConnection(host, port, ssl):
 
     def trySSL(cls,):
-        connect = cls(host, port)
+        ssl_context=sslmodule._create_unverified_context()
+        connect = cls(host, port, context=ssl_context)
         connect.connect()
         return connect
```

**Comment by skarra** [comment]
You might as well use http:// in that case :)

**Comment by DamienCassou** [comment]
https://trac.calendarserver.org/ticket/907

**Comment by gutosurrex** [comment]
One afternoon into asynk configurations just to find out there is no way to sync over self-signed certificates... For me this hands the whole thing useless.

A way to go around this issue would be to sync with a local .vcf file and let another software deal with the networking.

@skarra, congratulations for the software
