### ISSUE TITLE
AsynkError not imported from state_collection.py

### ISSUE THREAD

**Issue by DamienCassou** [skarra/ASynK#59]
```
Traceback (most recent call last):
  File "./asynk.py", line 302, in <module>
    main()
  File "./asynk.py", line 299, in main
    asynk.dispatch()
  File "/home/cassou/Downloads/asynk/asynk/asynk_core.py", line 97, in dispatch
    res = getattr(self, self.get_op())()
  File "/home/cassou/Downloads/asynk/asynk/asynk_core.py", line 366, in op_sync
    pname = self._load_profile()
  File "/home/cassou/Downloads/asynk/asynk/asynk_core.py", line 584, in _load_profile
    self._login()
  File "/home/cassou/Downloads/asynk/asynk/asynk_core.py", line 85, in _login
    coll.login()
  File "/home/cassou/Downloads/asynk/asynk/state_collection.py", line 291, in login
    raise AsynkError("%s: Cannot use any CardDAV accounts" % e)
NameError: global name 'AsynkError' is not defined
```

**Comment by skarra** [comment]
Can you update to tip of master now? I just pushed a minor change.

**Comment by DamienCassou** [comment]
This fixes my issue, thanks.
