### ISSUE TITLE
`AttributeError: n` while fetching contacts from cd to bb

### ISSUE THREAD

**Issue by DamienCassou** [skarra/ASynK#63]
I have a lot of contacts on a baikal carddav server and an *non existing* `~/.bbdb~. When I try to sync, I get:

```
$ ./asynk.py --op=sync --name carddav2bbdb --log=debug
[18:06:57.130     INFO] Last synk for profile carddav2bbdb was at: 2015-04-29T08:42:05.46Z
[18:06:57.130    DEBUG] Refreshing Contacts for folder default...
[18:06:58.023    DEBUG] Sending Request URL: /baikal/card.php/addressbooks/damiencnsa/default/	Method: PROPFIND
[18:06:58.746    DEBUG] Received Response: HTTP/1.1 207 Multi-status

[18:06:59.819    DEBUG] Sending Request URL: /baikal/card.php/addressbooks/damiencnsa/default/	Method: REPORT
[18:07:01.457    DEBUG] Received Response: HTTP/1.1 207 Multi-status

[18:07:02.031    ERROR] Error (n) parsing vCard object for 39845356-f109-4775-bf49-44399daa9930
[18:07:02.031 CRITICAL] Exception (n) while syncing profile carddav2bbdb
[18:07:02.032 CRITICAL] Traceback (most recent call last):
  File "/home/cassou/Documents/projects/asynk/asynk/asynk_core.py", line 396, in op_sync
    result = sync.sync(self.get_sync_dir())
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 295, in sync
    sl1, sl2 = self.prep_lists(dirn)
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 283, in prep_lists
    return self._prep_lists_2_way(self.get_f1(), self.get_f2())
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 178, in _prep_lists_2_way
    f1.prep_sync_lists(f2.get_dbid(), f1sl)
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 66, in prep_sync_lists
    curi  = self.get_itemids(pname, destid)
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 119, in get_itemids
    self._refresh_contacts()
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 313, in _refresh_contacts
    cons  = self.find_items(hrefs)
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 182, in find_items
    cd = CDContact(self, vco=vobject.readOne(vcf.text), itemid=key)
  File "/home/cassou/Documents/projects/asynk/asynk/contact_cd.py", line 99, in __init__
    self.init_props_from_vco(vco)
  File "/home/cassou/Documents/projects/asynk/asynk/contact_cd.py", line 178, in init_props_from_vco
    self._snarf_names_gender_from_vco(vco)
  File "/home/cassou/Documents/projects/asynk/asynk/contact_cd.py", line 225, in _snarf_names_gender_from_vco
    if vco.n and vco.n.value:
  File "/home/cassou/Documents/projects/asynk/lib/vobject/vobject/base.py", line 477, in __getattr__
    raise exceptions.AttributeError, name
AttributeError: n
```

My `state.json` is:
```json
{ "app_root" : "/home/cassou/Documents/projects/asynk",
  "asynk_user_dir" : "/home/cassou/.asynk",
  "default_profile" : "carddav2bbdb",
  "file_version" : 4,
  "profiles" : { "carddav2bbdb" : { "coll_1" : { "dbid" : "cd",
              "foid" : "default",
              "stid" : "https://www.schplaf.org/baikal/card.php"
            },
          "coll_2" : { "dbid" : "bb",
              "foid" : "default",
              "stid" : "/home/cassou/.bbdb"
            },
          "conflict_resolve" : "cd",
          "items" : { "e8d5bfefeab23559f5622b36ca5a7300a205f183f481f90b2be44202ce602854" : "a1b75163-ecb9-11e4-a5bf-406c8f5540b2" },
          "last_sync_start" : "2015-04-29T08:42:02.81Z",
          "last_sync_stop" : "2015-04-29T08:42:05.46Z",
          "olgid" : null,
          "sync_dir" : "SYNC2WAY",
          "sync_state" : null
        } }
```

**Comment by skarra** [comment]
Just pushed a fix to master. Can you check?

**Comment by DamienCassou** [comment]
Fixed, thanks!
