### ISSUE TITLE
AttributeError: 'list' object has no attribute 'strip'

### ISSUE THREAD

**Issue by DamienCassou** [skarra/ASynK#64]
I have a lot of contacts on a baikal carddav server and an non existing `~/.bbdb~. When I try to sync, I get:

```
$ ./asynk.py --op=sync --name carddav2bbdb --log=debug
[...]
[10:49:11.465    DEBUG] Successfully fetched and added contact: <One of my contacts>
[10:49:11.465    DEBUG] Successfully fetched and added contact: <One of my contacts>
[10:49:11.465 CRITICAL] Exception ('list' object has no attribute 'strip') while syncing profile carddav2bbdb
[10:49:11.465 CRITICAL] Traceback (most recent call last):
  File "/home/cassou/Documents/projects/asynk/asynk/asynk_core.py", line 396, in op_sync
    result = sync.sync(self.get_sync_dir())
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 295, in sync
    sl1, sl2 = self.prep_lists(dirn)
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 283, in prep_lists
    return self._prep_lists_2_way(self.get_f1(), self.get_f2())
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 178, in _prep_lists_2_way
    f1.prep_sync_lists(f2.get_dbid(), f1sl)
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 66, in prep_sync_lists
    curi  = self.get_itemids(pname, destid)
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 119, in get_itemids
    self._refresh_contacts()
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 318, in _refresh_contacts
    con.get_disp_name())
  File "/home/cassou/Documents/projects/asynk/asynk/contact.py", line 149, in get_disp_name
    self.get_lastname()] if x])
AttributeError: 'list' object has no attribute 'strip'
```

My `state.json` is:
```json
{ "app_root" : "/home/cassou/Documents/projects/asynk",
  "asynk_user_dir" : "/home/cassou/.asynk",
  "default_profile" : "carddav2bbdb",
  "file_version" : 4,
  "profiles" : { "carddav2bbdb" : { "coll_1" : { "dbid" : "cd",
              "foid" : "default",
              "stid" : "https://www.schplaf.org/baikal/card.php"
            },
          "coll_2" : { "dbid" : "bb",
              "foid" : "default",
              "stid" : "/home/cassou/.bbdb"
            },
          "conflict_resolve" : "cd",
          "items" : { "e8d5bfefeab23559f5622b36ca5a7300a205f183f481f90b2be44202ce602854" : "a1b75163-ecb9-11e4-a5bf-406c8f5540b2" },
          "last_sync_start" : "2015-04-29T08:42:02.81Z",
          "last_sync_stop" : "2015-04-29T08:42:05.46Z",
          "olgid" : null,
          "sync_dir" : "SYNC2WAY",
          "sync_state" : null
        } }
```

**Comment by skarra** [comment]
Interesting. This means I have not correctly handled a vCard format detail where firstname, lastname or middlename is parsed as an array instead of a single string.

Can you look at the entry, anonymise it and email that entry to me? I am more instructed in the structure of that entry.

**Comment by DamienCassou** [comment]
How do I get the raw entry? Is it possible through asynk? I've just tried:

```diff
--- a/asynk/contact_cd.py
+++ b/asynk/contact_cd.py
@@ -174,6 +174,7 @@ class CDContact(Contact):
     ## The Rest...
 
     def init_props_from_vco (self, vco):
+        logging.debug(vco)
         self._snarf_uid_from_vco(vco)
         self._snarf_names_gender_from_vco(vco)
         self._snarf_emails_from_vco(vco)
```

and I got:

```
[06:52:24.775    DEBUG] <VCARD| [<VERSION{}3.0>, <PRODID{}DAVdroid/0.7.3 (ez-vcard/0.9.6)>, <UID{}aabd8dd0-29a1-4fe7-abd3-5c831b365b83>, <EMAIL{u'TYPE': [u'home']}XXX@XXX.es>, <EMAIL{u'TYPE': [u'x-internet']}XXX@XXX.com>, <EMAIL{u'TYPE': [u'x-internet']}XXX@XXX.de>, <FN{}?XXX?s XXX XXX>, <N{} ?XXX XXX?X XXX XXX >, <REV{}20150429T204335Z>]>
```

Is that what you expect?

**Comment by skarra** [comment]
Could you replace that debug statement with the following two statements:

```
vco.prettyPrint()
vco.serialize()
```

**Comment by DamienCassou** [comment]
I have a different error now:

```
VCARD
    VERSION: 3.0
    REV: 20150429T204453Z
    UID: 39845356-f109-4775-bf49-44399daa9930
    PRODID: DAVdroid/0.7.3 (ez-vcard/0.9.6)
    EMAIL: XXX@XXX.com
    params for  EMAIL:
       TYPE [u'x-internet']

[21:21:41.529    ERROR] Error ('VCARD components must contain at least 1 FN') parsing vCard object for 39845356-f109-4775-bf49-44399daa9930
[21:21:41.529 CRITICAL] Exception ('VCARD components must contain at least 1 FN') while syncing profile carddav2bbdb
[21:21:41.530 CRITICAL] Traceback (most recent call last):
  File "/home/cassou/Documents/projects/asynk/asynk/asynk_core.py", line 396, in op_sync
    result = sync.sync(self.get_sync_dir())
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 295, in sync
    sl1, sl2 = self.prep_lists(dirn)
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 283, in prep_lists
    return self._prep_lists_2_way(self.get_f1(), self.get_f2())
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 178, in _prep_lists_2_way
    f1.prep_sync_lists(f2.get_dbid(), f1sl)
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 66, in prep_sync_lists
    curi  = self.get_itemids(pname, destid)
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 119, in get_itemids
    self._refresh_contacts()
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 313, in _refresh_contacts
    cons  = self.find_items(hrefs)
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 182, in find_items
    cd = CDContact(self, vco=vobject.readOne(vcf.text), itemid=key)
  File "/home/cassou/Documents/projects/asynk/asynk/contact_cd.py", line 99, in __init__
    self.init_props_from_vco(vco)
  File "/home/cassou/Documents/projects/asynk/asynk/contact_cd.py", line 178, in init_props_from_vco
    vco.serialize()
  File "/home/cassou/Documents/projects/asynk/lib/vobject/vobject/base.py", line 186, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/home/cassou/Documents/projects/asynk/lib/vobject/vobject/behavior.py", line 148, in serialize
    if validate: cls.validate(obj, raiseException=True)
  File "/home/cassou/Documents/projects/asynk/lib/vobject/vobject/behavior.py", line 91, in validate
    raise base.ValidateError(m % (cls.name, val[0], key))
ValidateError: 'VCARD components must contain at least 1 FN'
```

**Comment by skarra** [comment]
There's clearly something non-standard in your carddav vcf files, or the vobject library I am using has some bugs. Let's take it one at a time. Remove the serialize statment for now and let's see the last entry before the stack trace

**Comment by DamienCassou** [comment]
I think this is the one. In the N and FN fields, I replaced letters by X and I kept the ? characters (they seem to replace the accented characters of the contact name).

```
 VCARD
    UID: aabd8dd0-29a1-4fe7-abd3-5c831b365b83
    REV: 20150429T204335Z
    N:  ?XXX XXX?X XXXXXX XXXX 
    VERSION: 3.0
    FN: ?XXXX XXX?X XXXXXX XXXX
    EMAIL: XXX@XX.XX
    params for  EMAIL:
       TYPE [u'home']
    EMAIL: XXX@XX.com
    params for  EMAIL:
       TYPE [u'x-internet']
    EMAIL: XXX@XXX.XX
    params for  EMAIL:
       TYPE [u'x-internet']
    PRODID: DAVdroid/0.7.3 (ez-vcard/0.9.6)
```

**Comment by skarra** [comment]
I tried quite hard to reproduce the bug with teh above information, but failed to do so. The next thing you can try is to open your Baikal web interface and try exporting the problematic entry to an VCF directly and email me that. I would prefer if you do not chnage anything in the name fields - the rest can be masked / anonmised. You can email the entry to me if you wish.

**Comment by DamienCassou** [comment]
I'm using CardDavMATE and I don't see any way to export a contact.

**Comment by skarra** [comment]
What is your CadDAV Server? We may be able pull the contact from the server filesystem

**Comment by DamienCassou** [comment]
Sriram Karra <notifications@github.com> writes:

> What is your CadDAV Server? We may be able pull the contact from the
> server filesystem

Baikal

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by skarra** [comment]
@DamienCassou Thank you very much for sending the VCF file. I would never have managed to find that. I was able to reproduce the issue and have commited a fix to the ```cd-names``` branch. Can you test that and let me know if it works for you?

**Comment by DamienCassou** [comment]
This fixes my problem! Thank you very much.
