### ISSUE TITLE
AsynkParserError undefined in asynk_core.py

### ISSUE THREAD

**Issue by DamienCassou** [skarra/ASynK#65]
```
Traceback (most recent call last):
  File "./asynk.py", line 302, in <module>
    main()
  File "./asynk.py", line 299, in main
    asynk.dispatch()
  File "/home/cassou/Documents/projects/asynk/asynk/asynk_core.py", line 97, in dispatch
    res = getattr(self, self.get_op())()
  File "/home/cassou/Documents/projects/asynk/asynk/asynk_core.py", line 156, in op_show_folder
    raise AsynkParserError('--show-folder needs a --folder-id option')
asynk_core.AsynkParserError: --show-folder needs a --folder-id option
```

**Comment by skarra** [comment]
Can you paste the command line you used when the above error was thrown? From the above stack trace it just looks like expected behaviour. At this stage of ASynK development I am keeping stacktrace as the default way to communicate errors. It is based on the implicit assumption that current users of ASynK will be able to handle them :)

**Comment by DamienCassou** [comment]
I agree with you. I guess I was still too sleepy. Sorry.
