### ISSUE TITLE
Google Contacts, gdata, oauth

### ISSUE THREAD

**Issue by bradyt** [skarra/ASynK#68]
I encountered a problem to access Google Contacts via ASynK. 

Let me know if you would like the `stdout` from `--op=list-folders --db gc`. But I asked about it on the IRC Python channel, and they mentioned a few links that might illuminate what is happening here. 

So perhaps on April 20th, this app may have stopped working, because of items described here: 

from https://developers.google.com/gdata/docs/auth/clientlogin,
> ClientLogin is a deprecated authentication protocol and is being turned down on April 20, 2015. 

The gracious folks on the IRC also found a link to a possible workaround, at

https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=3850&colspec=Stars%20Opened%20ID%20Type%20Status%20Summary%20API%20Owner

Would this help with this issue? 

I have not made the time to learn much about programming, but I hoped I might be able to continue enjoying your software.

**Comment by bradyt** [comment]
For completeness, here is the command and traceback. 

    iam@heeere:~$ asynk --op=list-folders --db gc < ~/.netrc
    Applying base config from file /home/iam/my-src/ASynK/config/config_v7.json...
    Applying base config from file /home/iam/my-src/ASynK/config/config_v7.json...done
    Applying user customizations from file /home/iam/.asynk/config.py...
    Applying user customizations from file /home/iam/.asynk/config.py...done
    [22:37:28.560     INFO] Debug logging to file: /home/iam/.asynk/logs/asynk_logs.2015-05-30.22-37-28.560073
    [22:37:28.560     INFO] Deleting log files older than 7 days, if any...
    [22:37:28.560     INFO] Deleting log files older than 7 days, if any...done
    [22:37:28.561     INFO] Logging into Google...
    Please enter your username: Password: Traceback (most recent call last):
      File "/home/iam/my-src/ASynK/asynk.py", line 1125, in <module>
        main()
      File "/home/iam/my-src/ASynK/asynk.py", line 80, in main
        asynk.dispatch()
      File "/home/iam/my-src/ASynK/asynk.py", line 511, in dispatch
        res = getattr(self, self.get_op())()
      File "/home/iam/my-src/ASynK/asynk.py", line 526, in op_list_folders
        self._login()
      File "/home/iam/my-src/ASynK/asynk.py", line 300, in _login
        self.set_db(db1id, getattr(self, login_func)())
      File "/home/iam/my-src/ASynK/asynk.py", line 1044, in login_gc
        self.get_gcuser(), self.get_gcpw())
      File "/home/iam/my-src/ASynK/asynk/pimdb_gc.py", line 52, in __init__
        self.gc_init()
      File "/home/iam/my-src/ASynK/asynk/pimdb_gc.py", line 200, in gc_init
        gdc.ClientLogin(self.get_user(), self.get_pw(), gdc.source)
      File "/home/iam/.local/lib/python2.7/site-packages/gdata/client.py", line 441, in client_login
        captcha_token=captcha_token, captcha_response=captcha_response)
      File "/home/iam/.local/lib/python2.7/site-packages/gdata/client.py", line 373, in request_client_login_token
        response, ClientLoginFailed, response_body)
    gdata.client.ClientLoginFailed: Server responded to ClientLogin request: 404, https://developers.google.com/accounts/docs/AuthForInstalledApps
    
    iam@heeere:~$

**Comment by skarra** [comment]
I confirm this is a problem, and GC connector does not work in ASynK as of now. I am exploring ways to fix the situation.  Thank you for the pointers about workarounds.

**Comment by skarra** [comment]
I have pushed oAuth support to the ```gdata-oauth2``` branch. give that a shot. Also read the instructions here: https://github.com/skarra/ASynK/blob/gdata-oauth2/README-google-oauth.md before starting

**Comment by skarra** [comment]
Branch merged to master and included in v2.2.0-rc2 release
