### ISSUE TITLE
ValidateError: 'VCARD components must contain at least 1 FN'

### ISSUE THREAD

**Issue by DamienCassou** [skarra/ASynK#70]
```$ ./asynk.py --op=sync --name carddav2bbdb --log=debug
[...]
[10:01:41.936     INFO] Saving BBDB File /home/cassou/.bbdb...
[10:01:41.996     INFO] Saving BBDB File /home/cassou/.bbdb...done
[10:01:41.996     INFO] Writing sync state to CardDAV server...
[10:01:42.957    DEBUG] Sending Request URL: /baikal/card.php/addressbooks/damiencnsa/default/9d36fa60-bf15-4c2e-bea6-ceafe23d5225.vcf	Method: PUT
[10:01:43.766    DEBUG] Received Response: HTTP/1.1 204 No Content

[10:01:43.767 CRITICAL] Exception ('VCARD components must contain at least 1 FN') while syncing profile carddav2bbdb
[10:01:43.768 CRITICAL] Traceback (most recent call last):
  File "/home/cassou/Documents/projects/asynk/asynk/asynk_core.py", line 396, in op_sync
    result = sync.sync(self.get_sync_dir())
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 298, in sync
    ret1 = sl1.sync_to_folder(self.get_f2())
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 498, in sync_to_folder
    res1 = self.send_news_to_folder(df)
  File "/home/cassou/Documents/projects/asynk/asynk/sync.py", line 446, in send_news_to_folder
    res = res and self.fold.writeback_sync_tags(self.get_pname(), items)
  File "/home/cassou/Documents/projects/asynk/asynk/folder_cd.py", line 270, in writeback_sync_tags
    success = success and item.save()
  File "/home/cassou/Documents/projects/asynk/asynk/contact_cd.py", line 126, in save
    vcf_data = vco.serialize()
  File "/home/cassou/Documents/projects/asynk/lib/vobject/vobject/base.py", line 186, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/home/cassou/Documents/projects/asynk/lib/vobject/vobject/behavior.py", line 148, in serialize
    if validate: cls.validate(obj, raiseException=True)
  File "/home/cassou/Documents/projects/asynk/lib/vobject/vobject/behavior.py", line 91, in validate
    raise base.ValidateError(m % (cls.name, val[0], key))
ValidateError: 'VCARD components must contain at least 1 FN'
```

**Comment by skarra** [comment]
This seems to suggest you have at least one entry that does not have a name in your BBDB file. Can you confirm that? I can think of a work around to ensure this case is handled gracefully.

**Comment by skarra** [comment]
@DamienCassou I have pushed a fix to ```cd-names``` branch. Give it a shot.
