### ISSUE TITLE
Can't dry run sync between 2 carddav

### ISSUE THREAD

**Issue by DamienCassou** [skarra/ASynK#87]
```
$ asynk.py --op=sync --dry-run --name schplaf2brique --cduser XX XX --cdpwd XX XX
Applying base config from file /nix/store/7c0yvi5rc8ggm51g7hz0rr86zy1vgrc3-asynk-git/config/config_v8.json...
Applying base config from file /nix/store/7c0yvi5rc8ggm51g7hz0rr86zy1vgrc3-asynk-git/config/config_v8.json...done
Applying user customizations from file /home/cassou/.asynk/config.py...
Applying user customizations from file /home/cassou/.asynk/config.py...done
[12:06:25.345     INFO] Debug logging to file: /home/cassou/.asynk/logs/asynk_logs.2015-10-25.12-06-25.345193
Traceback (most recent call last):
  File "/nix/store/7c0yvi5rc8ggm51g7hz0rr86zy1vgrc3-asynk-git/bin/.asynk.py-wrapped", line 321, in <module>
    main()
  File "/nix/store/7c0yvi5rc8ggm51g7hz0rr86zy1vgrc3-asynk-git/bin/.asynk.py-wrapped", line 313, in main
    asynk = AsynkBuilderC(uinps, config, alogger).asynk
  File "/nix/store/7c0yvi5rc8ggm51g7hz0rr86zy1vgrc3-asynk-git/bin/.asynk.py-wrapped", line 178, in __init__
    self.validate_and_snarf_uinps(uinps)
  File "/nix/store/7c0yvi5rc8ggm51g7hz0rr86zy1vgrc3-asynk-git/bin/.asynk.py-wrapped", line 287, in validate_and_snarf_uinps
    self._snarf_auth_creds(uinps)
  File "/nix/store/7c0yvi5rc8ggm51g7hz0rr86zy1vgrc3-asynk-git/bin/.asynk.py-wrapped", line 220, in _snarf_auth_creds
    coll = self.asynk.get_colls()[i]
IndexError: list index out of range
```

This is my `state.json`

```json
      "schplaf2brique" : { "coll_1" : { "dbid" : "cd",
              "foid" : "1/",
              "stid" : "https://XX/baikal/card.php/addressbooks/XX/default"
            },
          "coll_2" : { "dbid" : "cd",
              "foid" : "1/",
              "stid" : "https://XX/baikal/card.php/addressbooks/XX/default"
            },
          "conflict_resolve" : "1",
          "last_sync_start" : "1980-01-01T00:00:00.00+00:00",
          "last_sync_stop" : "1980-01-01T00:00:00.00+00:00",
          "olgid" : null,
          "sync_dir" : "SYNC2WAY",
          "sync_state" : null
        }
```

**Comment by skarra** [comment]
I can reproduce the bug. As a workaround till I fix the bug can you use ~/.netrc with two entires like this:

```
machine cd1_profilename
	login ABC
	password yyy

machine cd2_profilename
	login DEF
	password xxx
```

**Comment by skarra** [comment]
Fixed in master. Please have a try
