### ISSUE TITLE
The simplest use case, the first recipe doesn’t work on a clean-state ~/.asynk/

### ISSUE THREAD

**Issue by michalrus** [skarra/ASynK#88]
In the line `Enter password for gc1: /home/m/.local/secret/mbsync` below, I’m entering the path to a file containing only the password in plain text. If I enter the password, **as suggested by the prompt text**, it errors with `oauth2client.clientsecrets.InvalidClientSecretsError: File not found: "/home/m/PASSWORD_HERE"`. (?!)

```
% rm -r ~/.asynk/
% python2 asynk.py --op=sync --log=debug
Creating ASynK User directory at:  /home/m/.asynk
Applying base config from file /home/m/.emacs.d/asynk/config/config_v8.json...
Applying base config from file /home/m/.emacs.d/asynk/config/config_v8.json...done
Applying user customizations from file /home/m/.asynk/config.py...
Applying user customizations from file /home/m/.asynk/config.py...done
INFO:root:Creating Logs directory at: /home/m/.asynk/logs
[01:22:50.694     INFO] Creating Logs directory at: /home/m/.asynk/logs
INFO:root:Debug logging to file: /home/m/.asynk/logs/asynk_logs.2015-10-31.01-22-50.694594
[01:22:50.694     INFO] Debug logging to file: /home/m/.asynk/logs/asynk_logs.2015-10-31.01-22-50.694594
DEBUG:root:Command line: ".emacs.d/asynk/asynk.py --op=sync --log=debug"
INFO:root:Deleting log files older than 7 days, if any...
[01:22:50.695     INFO] Deleting log files older than 7 days, if any...
INFO:root:Deleting log files older than 7 days, if any...done
[01:22:50.695     INFO] Deleting log files older than 7 days, if any...done
Please enter username for gc1: m@michalrus.com
Enter password for gc1: /home/m/.local/secret/mbsync
DEBUG:root:PIMDB gc does not have email_domains.
[01:23:13.638    DEBUG] PIMDB gc does not have email_domains.
DEBUG:root:PIMDB gc does not have notes_map
[01:23:13.638    DEBUG] PIMDB gc does not have notes_map
DEBUG:root:PIMDB gc does not have phones_map
[01:23:13.639    DEBUG] PIMDB gc does not have phones_map
INFO:root:Attempting to log into Google...
[01:23:13.639     INFO] Attempting to log into Google...
INFO:root:Starting to listen on port 1977...
[01:23:13.640     INFO] Starting to listen on port 1977...
INFO:root:Staring the wonderful oAuth dance...
[01:23:13.641     INFO] Staring the wonderful oAuth dance...
Traceback (most recent call last):
  File ".emacs.d/asynk/asynk.py", line 320, in <module>
    main()
  File ".emacs.d/asynk/asynk.py", line 317, in main
    asynk.dispatch()
  File "/home/m/.emacs.d/asynk/asynk/asynk_core.py", line 97, in dispatch
    res = getattr(self, self.get_op())()
  File "/home/m/.emacs.d/asynk/asynk/asynk_core.py", line 366, in op_sync
    pname = self._load_profile()
  File "/home/m/.emacs.d/asynk/asynk/asynk_core.py", line 590, in _load_profile
    self._login()
  File "/home/m/.emacs.d/asynk/asynk/asynk_core.py", line 85, in _login
    coll.login()
  File "/home/m/.emacs.d/asynk/asynk/state_collection.py", line 336, in login
    self.get_username(), self.get_pwd())
  File "/home/m/.emacs.d/asynk/asynk/pimdb_gc.py", line 71, in __init__
    self.gc_init()
  File "/home/m/.emacs.d/asynk/asynk/pimdb_gc.py", line 279, in gc_init
    self.credentials = self._oauth_dance(storage)
  File "/home/m/.emacs.d/asynk/asynk/pimdb_gc.py", line 257, in _oauth_dance
    redirect_uri='http://localhost:%d' % port)
  File "/usr/lib/python2.7/site-packages/oauth2client/util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 2210, in flow_from_clientsecrets
    cache=cache)
  File "/usr/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/usr/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 123, in _loadfile
    obj = json.load(fp)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

And then it hangs indefinitely. Versions:

```
% pacman -Q | grep 'python2' | grep -E 'http|google|oauth|ssl|python2 '
python2 2.7.10-2
python2-google-api-python-client 1.4.2-1
python2-httplib2 0.9.2-1
python2-oauth2client 1.5.1-1
python2-pyopenssl 0.15.1-2
% cd asynk && git rev-parse HEAD
421a3e9c8f219d252c805cedebe176f7ec2520aa
% 
```

What should I do now, @skarra?

**Comment by skarra** [comment]
I am sorry the documentation is not up to date. Google disabled the simple password based authentication mechanism and you cannot sync to google without setting up the oauth credentials as explained here: https://github.com/skarra/ASynK/blob/master/README-google-oauth.md

There is no "simple" way to sync to / from Google any more for reasons beyond my control.

**Comment by michalrus** [comment]
@skarra, thank you. :smiley_cat:
