### ISSUE TITLE
Syncing a(n empty) bbdb file with the default profile not working

### ISSUE THREAD

**Issue by dieter-wilhelm** [skarra/ASynK#97]
I'm trying 
$ ./asynk.py --op=sync --dry-run
with the default profile and receive below debug information. It seems to work well for the google side but I don't understand the line with fid1=none, how do I specify a gc folder?.

```
Applying base config from file /appl/tools/ASynK-2.2.0/config/config_v7.json...
Applying base config from file /appl/tools/ASynK-2.2.0/config/config_v7.json...done
Applying user customizations from file /home/dieter/.asynk/config.py...
Applying user customizations from file /home/dieter/.asynk/config.py...done
INFO:root:Debug logging to file: /home/dieter/.asynk/logs/asynk_logs.2016-06-03.08-43-08.152349
[08:43:08.152     INFO] Debug logging to file: /home/dieter/.asynk/logs/asynk_logs.2016-06-03.08-43-08.152349
DEBUG:root:Command line: "./asynk.py --op=sync --dry-run"
Please enter username for gc1: dieter.wilhelm
Enter password for gc1: ~/.asynk/oauth.json
DEBUG:root:PIMDB gc does not have email_domains.
DEBUG:root:PIMDB gc does not have notes_map
DEBUG:root:PIMDB gc does not have phones_map
INFO:root:Attempting to log into Google...
[08:43:22.022     INFO] Attempting to log into Google...
INFO:root:Using pre-fetched access_token...
[08:43:22.026     INFO] Using pre-fetched access_token...
DEBUG:root:Getting Group List to populate folders...
DEBUG:root:Processing Folder: System Group: My Contacts...
DEBUG:root:Processing Folder: System Group: Friends...
DEBUG:root:Processing Folder: System Group: Family...
DEBUG:root:Processing Folder: System Group: Coworkers...
DEBUG:root:Processing Folder: dancing...
DEBUG:root:Processing Folder: YouTube...
DEBUG:root:Processing Folder: Starred in Android...
DEBUG:root:Processing Folder: Importation du 27/01/13...
DEBUG:root:Processing Folder: ICE...
INFO:root:Parsing BBDB file /home/dieter/.bbdb...
[08:43:22.266     INFO] Parsing BBDB file /home/dieter/.bbdb...
DEBUG:root:New BBContactsFolder: default
INFO:root:Parsing BBDB Store with encoding utf-8...
[08:43:22.266     INFO] Parsing BBDB Store with encoding utf-8...
INFO:root:Parsing BBDB Store with encoding utf-8...Success
[08:43:22.267     INFO] Parsing BBDB Store with encoding utf-8...Success
INFO:root:Successfully parsed 0 entries.
[08:43:22.267     INFO] Successfully parsed 0 entries.
DEBUG:root:pimdbs : [<pimdb_gc.GCPIMDB object at 0x7f0220de0950>, <pimdb_bb.BBPIMDB object at 0x7f0220e06990>]
DEBUG:root:pname : defgcbb
DEBUG:root:fid1  : None
DEBUG:root:fid2  : default
DEBUG:root:db1id : gc
DEBUG:root:db    : <pimdb_gc.GCPIMDB object at 0x7f0220de0950>
DEBUG:root:Updated fid2  : default
ERROR:root:Could not find folder with ID fid1: None
[08:43:22.268    ERROR] Could not find folder with ID fid1: None
Traceback (most recent call last):
  File "./asynk.py", line 321, in <module>
    main()
  File "./asynk.py", line 318, in main
    asynk.dispatch()
  File "/appl/tools/ASynK-2.2.0/asynk/asynk_core.py", line 97, in dispatch
    res = getattr(self, self.get_op())()
  File "/appl/tools/ASynK-2.2.0/asynk/asynk_core.py", line 385, in op_sync
    dr=self.is_dry_run())
  File "/appl/tools/ASynK-2.2.0/asynk/sync.py", line 83, in __init__
    raise Exception()
Exception
```

When I'm trying to specify a folder like:
$ ./asynk.py --op=sync --folder 'http://www.google.com/m8/feeds/groups/dieter.wilhelm%40gmail.com/base/6' --dry-run         

I'm getting:

```
Applying base config from file /appl/tools/ASynK-2.2.0/config/config_v7.json...
Applying base config from file /appl/tools/ASynK-2.2.0/config/config_v7.json...done
Applying user customizations from file /home/dieter/.asynk/config.py...
Applying user customizations from file /home/dieter/.asynk/config.py...done
INFO:root:Debug logging to file: /home/dieter/.asynk/logs/asynk_logs.2016-06-03.09-08-44.703873
[09:08:44.703     INFO] Debug logging to file: /home/dieter/.asynk/logs/asynk_logs.2016-06-03.09-08-44.703873
DEBUG:root:Command line: "./asynk.py --op=sync --folder http://www.google.com/m8/feeds/groups/dieter.wilhelm%40gmail.com/base/6 --dry-run"
Traceback (most recent call last):
  File "./asynk.py", line 321, in <module>
    main()
  File "./asynk.py", line 313, in main
    asynk = AsynkBuilderC(uinps, config, alogger).asynk
  File "./asynk.py", line 178, in __init__
    self.validate_and_snarf_uinps(uinps)
  File "./asynk.py", line 288, in validate_and_snarf_uinps
    self._snarf_folder_ids(uinps)
  File "./asynk.py", line 239, in _snarf_folder_ids
    coll = self.asynk.get_colls()[i]
IndexError: list index out of range

```

**Comment by skarra** [comment]
Firstly I am sorry setting up and using ASynK is so hard. Simplicity was not a design objective when building this. I have some plans that will unfold in the coming months (if not years :) to address this usability issue.

More specifically, you need to specify the folder at the time of creating a profile. The above errors show that your profile does not have any folder specified. Can you take a look at these recipes and see if that helps? http://asynk.io/doc/asynk/asynk_6.html

**Comment by dieter-wilhelm** [comment]
Thanks, I'll try to setup a profile over the weekend.

By the way, my ultimate goal is to sync bbdb with ownCloud contacts...

**Comment by skarra** [comment]
That's possible. You can sync directly from Google to ownCloud too

**Comment by dieter-wilhelm** [comment]
@skarra please close this issue, I created a profile according to your documentation and I managed to sync a google contact folder with a(n empty) bbdb file. :-)

Another question, how do I specify multiple folder IDs in my profile?  Do I have to add multiple foid lines or just separate foids in one line with commas?

Thank you for your encouragements. My next step is to create a profile for a cd store with bbdb...
