### ISSUE TITLE
syncing with cardDav not working

### ISSUE THREAD

**Issue by dieter-wilhelm** [skarra/ASynK#99]
I created a profile for syncing with bbdb and cardDav. Unfortunately there is still a module named "vobject" missing, please tell me how I should load it:

```
Traceback (most recent call last):
  File "./asynk.py", line 321, in <module>
    main()
  File "./asynk.py", line 318, in main
    asynk.dispatch()
  File "/appl/tools/ASynK-2.2.0/asynk/asynk_core.py", line 97, in dispatch
    res = getattr(self, self.get_op())()
  File "/appl/tools/ASynK-2.2.0/asynk/asynk_core.py", line 366, in op_sync
    pname = self._load_profile()
  File "/appl/tools/ASynK-2.2.0/asynk/asynk_core.py", line 590, in _load_profile
    self._login()
  File "/appl/tools/ASynK-2.2.0/asynk/asynk_core.py", line 85, in _login
    coll.login()
  File "/appl/tools/ASynK-2.2.0/asynk/state_collection.py", line 291, in login
    raise AsynkCollectionError("%s: Cannot use any CardDAV accounts" % e)
state_collection.AsynkCollectionError: No module named vobject: Cannot use any CardDAV ac
counts                                                     
```

**Comment by skarra** [comment]
I think you have still not done a recursive clone. vobject is a submodule of ASynK

**Comment by dieter-wilhelm** [comment]
No I haven't.  Maybe this is a wrong interpretation of the conversion in issue #93 between you and  @vincentbernat and the renaming of the issue. I thought I'm supposed to test the usage of release 2.2.0 under Debian (to make a Debian package out of it). So far Vincent helped me to find the right Debian packages for missing modules...
But I've also no problem fetching the latest development version with git...

Thank you

**Comment by skarra** [comment]
Try just updating your submodules with:

```
git submodule update --init --recursive
```

**Comment by skarra** [comment]
Closing as there is no update for long.
